spring.application.name=config-server
server.port=8888

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Use classpath for config files (no Git needed)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configs/
